name: Acceptance Tests

on: [ push, pull_request ]

jobs:
  Acceptance:
    runs-on: ubuntu-18.04    # supported: ubuntu-16.04 and ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        typo3: [ ^9.5, ^10.4 ]
    steps:

      - name: "Determine Branch name (merge)"
        id: "determine-branch"
        if: github.event_name != 'pull_request'
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/heads/}\""

      - name: "Determine Branch name (pr)"
        id: "determine-branch"
        if: github.event_name == 'pull_request'
        run: "echo \"::set-output name=tag::${GITHUB_HEAD_REF}\""

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Version information
        run: |
          php -v
          composer --version

      - uses: actions/checkout@v1
      - uses: jonaseberle/github-action-setup-ddev@v1
        with:
          ddevDir: ".devbox"
      - run: |
          cd .devbox
          rm -rf vendor composer.lock
          ddev composer require aoepeople/crawler:dev-${{ steps.determine-branch.outputs.tag }} nimut/typo3-complete=${{ matrix.typo3 }}
          ddev start
          ddev exec bin/typo3cms install:fixfolderstructure
          ddev exec bin/typo3cms install:extensionsetupifpossible
          ddev exec bin/typo3cms database:updateschema
          ddev exec bin/typo3cms cache:flush
          cd .. # Going back to "root" directory
          rm -rf .Build composer.lock
          composer require nimut/typo3-complete=${{ matrix.typo3 }}
          wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          docker ps
          ./wait-for-it.sh -t 60 127.0.0.1:80
          ./wait-for-it.sh -t 60 127.0.0.1:443
          ./wait-for-it.sh -t 60 localhost:4444
          php .Build/bin/codecept run

      - name: Upload Codeception output
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: codeception-results
          path: Tests/Acceptance/_output/

      - uses: shallwefootball/s3-upload-action@master
        if: ${{ failure() }}
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'Tests/Acceptance/_output/'
          destination_dir: ''
