name: Static Analysis

on: [push, pull_request]

jobs:
    phpstan:
        name: PHPstan
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
            -   run: composer install --no-progress
            -   run: composer analyse

    rector:
        name: Rector
        runs-on: ubuntu-latest
        steps:
              -   uses: actions/checkout@v2
              -   id: composer-cache
                  run: echo "::set-output name=dir::$(composer config cache-files-dir)"
              -   uses: actions/cache@v1
                  with:
                      path: ${{ steps.composer-cache.outputs.dir }}
                      key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                      restore-keys: |
                          ${{ runner.os }}-composer-
              -   uses: shivammathur/setup-php@v2
                  with:
                      php-version: 7.4
                      coverage: none
              -   run: composer install --no-progress
              -   run: composer rector

    code-style:
        name: Code Style
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
            -   run: composer install --no-progress
            -   run: composer cs-fix

    Sonar-cloud:
        name: Sonar Cloud
        on:
            push:
                branches:
                    - master
                    - sonarqube
                    - github-actions
        steps:
             -   uses: actions/checkout@v2
             -   id: composer-cache
                 run: echo "::set-output name=dir::$(composer config cache-files-dir)"
             -   uses: actions/cache@v1
                 with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                       ${{ runner.os }}-composer-
             -   uses: shivammathur/setup-php@v2
                 with:
                    php-version: 7.4
                    coverage: none
             -   run: |
                    if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
                        composer require --dev nimut/typo3-complete:^9.5 --no-progress
                        export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
                        export "UNIT_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml'
                        export "FUNCTIONAL_XML"='.Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml'
                        mkdir -p .Logs/coverage .Logs/junit
                        .Build/bin/phpunit --whitelist Classes --coverage-php .Logs/coverage/unit_clover.cov --log-junit .Logs/junit/unit_junit.xml -c $UNIT_XML Tests/Unit
                        .Build/bin/phpunit --whitelist Classes --coverage-php .Logs/coverage/functional-coverage.cov --log-junit .Logs/junit/functional-junit.xml -c $FUNCTIONAL_XML Tests/Functional
                        .Build/bin/phpunit-merger coverage .Logs/coverage/ .Logs/coverage.xml;
                        .Build/bin/phpunit-merger log .Logs/junit/ .Logs/junit.xml;
                    fi
                 env:
                    typo3DatabaseHost: 127.0.0.1
                    typo3DatabaseName: typo3
                    typo3DatabasePassword: root
                    typo3DatabaseUsername: root
